name: Find modules in the repository
description: >
  Looks for modules in the repository and outputs their paths.

outputs:
  tf-modules:
    description: Paths to the Terraform modules found in the repository
    value: ${{ steps.find-modules.outputs.tf-modules }}

runs:
  using: composite
  steps:
    - name: Find modules
      id: find-modules
      run: |
        tf_modules=$(./.github/scripts/collect-modules.sh)
        echo tf-modules=$(printf '%s\n' "${tf_modules[@]}" | jq -cnR '[inputs]') > $GITHUB_OUTPUT
      shell: bash
