name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  collect-modules:
    runs-on: ubuntu-latest
    outputs:
      tf-modules: ${{ steps.collect-modules.outputs.tf-modules }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/collect-modules
        id: collect-modules

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.30.2

  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ^1
          terraform_wrapper: false

      - run: terraform fmt -check

  terraform-validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - asset-account/terraform/stack-set/examples/self-managed
          - asset-account/terraform/stack-set/examples/service-managed

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ^1
          terraform_wrapper: false

      - run: terraform init -input=false
        working-directory: ${{ matrix.project }}

      - run: terraform validate
        working-directory: ${{ matrix.project }}

  terraform-docs:
    runs-on: ubuntu-latest
    needs:
      - collect-modules

    strategy:
      matrix:
        terraform_module: ${{fromJson(needs.collect-modules.outputs.tf-modules)}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci --ignore-scripts

      - run: |
          curl https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz \
            --location \
            --silent \
            --retry 5 \
            --retry-all-errors \
            --show-error \
            | tar -xz terraform-docs > ./terraform-docs
        working-directory: ${{ matrix.terraform_module }}

      - run: chmod +x ./terraform-docs
        working-directory: ${{ matrix.terraform_module }}

      - run: ./terraform-docs markdown . --output-file README.md
        working-directory: ${{ matrix.terraform_module }}

      - run: npx prettier -w .

      - run: >-
          git diff --exit-code --color=always || ( echo "Terraform docs are
          out-of-date. See the diff above." && exit 1 )

  tflint:
    runs-on: ubuntu-latest

    env:
      TFLINT_CONFIG_FILE: "${{ github.workspace }}/.tflint.hcl"

    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "latest"

      - run: tflint --init
      - run: tflint --color --recursive

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npx prettier --check .
