name: release

on:
  workflow_dispatch:
  pull_request:

jobs:
  collect-modules:
    runs-on: ubuntu-latest
    outputs:
      tf-modules: ${{ steps.collect-modules.outputs.tf-modules }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/collect-modules
        id: collect-modules

  release-module:
    runs-on: ubuntu-latest
    needs: ["collect-modules"]
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        module: ${{fromJson(needs.collect-modules.outputs.tf-modules)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: git config user.name "Tsar Ferris"
      - run: git config user.email tsar-ferris@elastio.com

      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_TOKEN }}

      - name: release module
        run: |
          .github/scripts/release-tf-module.sh \
            --module-path ${{ matrix.module }} \
            --publish \
            --tag-push
