name: release

on:
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      tf-modules: ${{ steps.meta.outputs.tf-modules }}
      tf-examples: ${{ steps.meta.outputs.tf-examples }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/collect-meta
        id: meta

  release-module:
    runs-on: ubuntu-latest
    needs: [meta]
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        module: ${{fromJson(needs.meta.outputs.tf-modules)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: git config user.name "Tsar Ferris"
      - run: git config user.email tsar-ferris@elastio.com

      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_TOKEN }}

      - name: release module
        run: |
          .github/scripts/release-tf-module.sh \
            --module-path ${{ matrix.module }} \
            --publish \
            --tag-push
